<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2014 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$vardefs = array(
    'fields' =>
        array(
            'stage' =>
                array(
                    'required' => false,
                    'name' => 'stage',
                    'vname' => 'LBL_STAGE',
                    'type' => 'enum',
                    'dbType' => 'varchar',
                    'massupdate' => false,
                    'default' => '',
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 100,
                    'size' => '20',
                    'options' => 'listing_dynamic_stage_list',
                    'studio' => 'visible',
                    'dependency' => false,
                ),
            'iems_project_id_c' =>
                array(
                    'required' => false,
                    'name' => 'iems_project_id_c',
                    'vname' => 'LBL_PROJECT_IEMS_PROJECT_ID',
                    'type' => 'id',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => 0,
                    'audited' => false,
                    'reportable' => false,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 36,
                    'size' => '20',
                ),
            'project' =>
                array(
                    'required' => false,
                    'source' => 'non-db',
                    'name' => 'project',
                    'vname' => 'LBL_PROJECT',
                    'type' => 'relate',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                    'id_name' => 'iems_project_id_c',
                    'ext2' => 'iems_Project',
                    'module' => 'iems_Project',
                    'rname' => 'name',
                    'quicksearch' => 'enabled',
                    'studio' => false,
                ),
            'buildings' =>
                array(
                    'required' => false,
                    'name' => 'buildings',
                    'vname' => 'LBL_BUILDINGS',
                    'type' => 'varchar',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => false,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'full_text_search' =>
                        array(
                            'boost' => '0',
                        ),
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                ),
            'date_c' =>
                array(
                    'required' => false,
                    'name' => 'date_c',
                    'vname' => 'LBL_DATE_C',
                    'type' => 'date',
                    'massupdate' => '1',
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'size' => '20',
                    'enable_range_search' => false,
                ),
            'approved_by' =>
                array(
                    'required' => false,
                    'name' => 'approved_by',
                    'vname' => 'LBL_APPROVED_BY',
                    'type' => 'varchar',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'full_text_search' =>
                        array(
                            'boost' => '0',
                        ),
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                ),
            'send_email' =>
                array(
                    'required' => false,
                    'name' => 'send_email',
                    'vname' => 'LBL_SEND_EMAIL',
                    'type' => 'bool',
                    'massupdate' => 0,
                    'default' => '0',
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                ),
            'iems_title_id_c' =>
                array(
                    'required' => false,
                    'name' => 'iems_title_id_c',
                    'vname' => 'LBL_TITLE_IEMS_TITLE_ID',
                    'type' => 'id',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => 0,
                    'audited' => false,
                    'reportable' => false,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 36,
                    'size' => '20',
                ),
            'title' =>
                array(
                    'required' => false,
                    'source' => 'non-db',
                    'name' => 'title',
                    'vname' => 'LBL_TITLE',
                    'type' => 'relate',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                    'id_name' => 'iems_title_id_c',
                    'ext2' => 'iems_Title',
                    'module' => 'iems_Title',
                    'rname' => 'name',
                    'quicksearch' => 'enabled',
                    'studio' => 'visible',
                ),
            'deposited_plan' =>
                array(
                    'required' => false,
                    'name' => 'deposited_plan',
                    'vname' => 'LBL_DEPOSITED_PLAN',
                    'type' => 'varchar',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'full_text_search' =>
                        array(
                            'boost' => '0',
                        ),
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                ),
            'released' =>
                array(
                    'required' => false,
                    'name' => 'released',
                    'vname' => 'LBL_RELEASED',
                    'type' => 'enum',
                    'massupdate' => '1',
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 100,
                    'size' => '20',
                    'options' => 'released_list',
                    'studio' => 'visible',
                    'dependency' => false,
                ),
            'wordpress_post_id' =>
                array(
                    'required' => false,
                    'name' => 'wordpress_post_id',
                    'vname' => 'LBL_WORDPRESS_POST_ID',
                    'type' => 'id',
                ),
            'document' =>
                array(
                    'name' => 'document',
                    'vname' => 'LBL_DOCUMENT',
                    'type' => 'file',
                    'comment' => 'The filename of the document attachment',
                    'required' => false,
                    'noChange' => true,
                    'allowEapm' => true,
                    'fileId' => 'document_revision_id',
                    'docType' => 'doc_type',
                    'docUrl' => 'doc_url',
                    'docId' => 'doc_id',
                    'massupdate' => false,
                    'no_default' => false,
                    'comments' => 'The filename of the document attachment',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                ),
            'document_revision_id' =>
                array(
                    'name' => 'document_revision_id',
                    'vname' => 'LBL_DOCUMENT_REVISION_ID',
                    'type' => 'varchar',
                    'len' => '36',
                    'reportable' => true,
                    'required' => false,
                    'massupdate' => false,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'full_text_search' =>
                        array(
                            'boost' => '0',
                        ),
                    'calculated' => false,
                    'size' => '20',
                ),
        ),
    'relationships' =>
        array(),
);