<?php
$dictionary['Document']['fields']['attach_to_contract'] = array(
    'required' => false,
    'name' => 'attach_to_contract',
    'vname' => 'LBL_ATTACH_TO_CONTRACT',
    'type' => 'enum',
    'massupdate' => 0,
    'default' => 'no',
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => true,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'len' => 100,
    'size' => '20',
    'options' => 'document_attach_to_contract',
    'studio' => 'visible',
    'dependency' => false,
);