<?php
$dictionary['Document']['fields']['display_in_web_pages'] = array(
    'required' => false,
    'name' => 'display_in_web_pages',
    'vname' => 'LBL_DISPLAY_IN_WEB_PAGES',
    'type' => 'multienum',
    'massupdate' => true,
    'no_default' => false,
    'comments' => '',
    'help' => '',
    'importable' => 'true',
    'duplicate_merge' => 'disabled',
    'duplicate_merge_dom_value' => '0',
    'audited' => false,
    'reportable' => true,
    'unified_search' => false,
    'merge_filter' => 'disabled',
    'calculated' => false,
    'size' => '20',
    'options' => 'document_display_in_web_pages',
    'studio' => 'visible',
    'dependency' => '',
    'isMultiSelect' => true,
);