<?php
/*********************************************************************************
 * By installing or using this file, you are confirming on behalf of the entity
 * subscribed to the SugarCRM Inc. product ("Company") that Company is bound by
 * the SugarCRM Inc. Master Subscription Agreement (“MSA”), which is viewable at:
 * http://www.sugarcrm.com/master-subscription-agreement
 *
 * If Company is not bound by the MSA, then by installing or using this file
 * you are agreeing unconditionally that Company will be bound by the MSA and
 * certifying that you have authority to bind Company accordingly.
 *
 * Copyright (C) 2004-2014 SugarCRM Inc.  All rights reserved.
 ********************************************************************************/

$vardefs = array(
    'fields' =>
        array(
            'role' =>
                array(
                    'required' => false,
                    'name' => 'role',
                    'vname' => 'LBL_ROLE',
                    'type' => 'enum',
                    'massupdate' => true,
                    'default' => 'referral_partner',
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 100,
                    'size' => '20',
                    'options' => 'project_contacts_list',
                    'studio' => 'visible',
                    'dependency' => false,
                ),
            'parent_name' =>
                array(
                    'required' => false,
                    'source' => 'non-db',
                    'name' => 'parent_name',
                    'vname' => 'LBL_FLEX_RELATE',
                    'type' => 'parent',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 25,
                    'size' => '20',
                    'options' => 'project_contact_allowed_modules',
                    'studio' => 'visible',
                    'type_name' => 'parent_type',
                    'id_name' => 'parent_id',
                    'parent_type' => 'record_type_display',
                    'populate_list' =>
                        array(
                            'email1' => 'email1',
                            'phone_mobile' => 'phone_mobile',
                            'phone_office' => 'phone_office',
                        ),
                ),
            'parent_type' =>
                array(
                    'required' => false,
                    'name' => 'parent_type',
                    'vname' => 'LBL_PARENT_TYPE',
                    'type' => 'parent_type',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => 0,
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 255,
                    'size' => '20',
                    'dbType' => 'varchar',
                    'studio' => 'hidden',
                ),
            'parent_id' =>
                array(
                    'required' => false,
                    'name' => 'parent_id',
                    'vname' => 'LBL_PARENT_ID',
                    'type' => 'id',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => 0,
                    'audited' => false,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 36,
                    'size' => '20',
                ),
            'iems_parent_id' =>
                array(
                    'required' => false,
                    'name' => 'iems_parent_id',
                    'vname' => 'LBL_PROJECT_IEMS_PROJECT_ID',
                    'type' => 'id',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'true',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => 0,
                    'audited' => true,
                    'reportable' => false,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'calculated' => false,
                    'len' => 36,
                    'size' => '20',
                ),
            'phone_mobile' =>
                array(
                    'required' => false,
                    'name' => 'phone_mobile',
                    'vname' => 'LBL_PHONE_MOBILE',
                    'type' => 'varchar',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'false',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'full_text_search' =>
                        array(
                            'boost' => '0',
                        ),
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                    'formula' => '',
                    'enforced' => true,
                    'readonly' => true,
                    'source' => 'non-db',
                ),
            'phone_office' =>
                array(
                    'required' => false,
                    'name' => 'phone_office',
                    'vname' => 'LBL_PHONE_OFFICE',
                    'type' => 'varchar',
                    'massupdate' => 0,
                    'no_default' => false,
                    'comments' => '',
                    'help' => '',
                    'importable' => 'false',
                    'duplicate_merge' => 'disabled',
                    'duplicate_merge_dom_value' => '0',
                    'audited' => true,
                    'reportable' => true,
                    'unified_search' => false,
                    'merge_filter' => 'disabled',
                    'full_text_search' =>
                        array(
                            'boost' => '0',
                        ),
                    'calculated' => false,
                    'len' => '255',
                    'size' => '20',
                    'formula' => '',
                    'enforced' => true,
                    'readonly' => true,
                    'source' => 'non-db',
                ),
            'email1' =>
                array(
                    'required' => false,
                    'name' => 'email1',
                    'vname' => 'LBL_EMAIL1',
                    'type' => 'varchar',
                    'massupdate' => 0,
                    'no_default' => false,
                    'audited' => true,
                    'reportable' => true,
                    'readonly' => true,
                    'source' => 'non-db',
                ),
        ),
    'relationships' =>
        array(),
);