<?php
$viewdefs['iems_Project']['base']['filter']['default'] = array(
    'default_filter' => 'all_records',
    'fields' =>
        array(
            'name' => array(),
            'assigned_user_name' => array(),
            '$owner' => array(
                'predefined_filter' => true,
                'vname' => 'LBL_CURRENT_USER_FILTER',
            ),
            '$favorite' =>  array(
                'predefined_filter' => true,
                'vname' => 'LBL_FAVORITES_FILTER',
            ),
            'modified_by_name' =>   array(),
            'titles_expected' =>    array(),
            'vendor' => array(),
            'created_by_name' =>    array(),
            'iems_project_iems_pricing_name' => array(),
            'build_status_land_settled' =>  array(),
            'ucv_valuer' => array(),
            'ucv_valued' => array(),
            'ucv_value' =>  array(),
            'property_valuer' =>    array(),
            'property_valued' =>    array(),
            'land_value' => array(),
            'property_value' => array(),
            'land_valuer' =>    array(),
            'land_valued' =>    array(),
            'build_status_finished' =>  array(),
            'client_file_number' => array(),
            'build_status_lockup' =>    array(),
            'build_status_practical_comp' =>    array(),
            'build_status_fitout' =>    array(),
            'build_status_roof_cover' =>    array(),
            'build_status_plate_frame' =>   array(),
            'build_status_slab' =>  array(),
            'build_status_con_started' =>   array(),
            'facilities' => array(),
            'marketing_status_abandoned' => array(),
            'marketing_status_selling' =>   array(),
            'marketing_status_sold' =>  array(),
            'marketing_status_finance_approved' =>  array(),
            'marketing_status_marketing' => array(),
            'marketing_status_listed' =>    array(),
            'marketing_status_on_hold' =>   array(),
            'marketing_status_planning' =>  array(),
            'marketing_status_percent_win' =>   array(),
            'marketing_status_appraisal' => array(),
            'build_status' =>   array(),
            'marketing_status' =>   array(),
            'completed' =>  array(),
            'primary_address_country' =>    array(),
            'primary_address_state' =>  array(),
            'primary_address_postalcode' => array(),
            'primary_address_city' =>   array(),
            'title_released' => array(),
            'primary_address_street' => array(),
            'expected_completion' =>    array(),
            'views' =>  array(),
            'construction' =>   array(),
            'levels' => array(),
            'aspect' => array(),
            'property_type' =>  array(),
            'estate_disclaimer' =>  array(),
            'stages' => array(),
            'title' =>  array(),
            'registration' =>   array(
                'options' => 'filter_checkbox_dom',
            ),
            'duration' =>   array(),
            'builder' =>    array(),
            'sunset_date' =>    array(),
            'buildings' =>  array(),
            'featured' =>   array(
                'options' => 'filter_checkbox_dom',
            ),
            'show_on_web' =>    array(
                'options' => 'filter_checkbox_dom',
            ),
            'is_master_project' =>  array(
                'options' => 'filter_checkbox_dom',
            ),
            'agreement_finish' =>   array(),
            'agreement_start' =>    array(),
            'dwellings' =>  array(),
            'project_id' => array(),
            'multiple_house_designs' => array(),
            'titles_released' => array(),
            'date_modified' => array(),
            'description' => array(),
            'website' => array(
                'dbFields' => array(
                    'website_url',
                ),
                'vname' => 'LBL_WEBSITE_URL',
                'type' => 'text',
            ),
            'web_display_order' => array(),
            'primary_address_lot_number' => array(),
            'primary_address_street_number' => array(),
            'primary_address_street_name' => array(),
            'primary_address_suburb' => array(),
            'parent_name' => array(),
            'date_entered' => array(),
            'master_project' => array(),
            'team_name' => array(),
            'custom_referrer_account' => array(
                'dbFields' => array(
                    'referrer_account.name',
                ),
                'vname' => 'LBL_REFERRER_ACCOUNT',
                'type' => 'text',
            ),
            'custom_referrer_contact' => array(
                'dbFields' => array(
                    'referrer_contact.full_name_c',
                    'referrer_contact.last_name',
                    'referrer_contact.first_name',
                ),
                'vname' => 'LBL_REFERRER_CONTACT',
                'type' => 'text',
            ),
            'custom_builder_account' => array(
                'dbFields' => array(
                    'builder_account.name',
                ),
                'vname' => 'LBL_BUILDER_ACCOUNT',
                'type' => 'text',
            ),
            'custom_builder_contact' => array(
                'dbFields' => array(
                    'builder_contact.full_name_c',
                    'builder_contact.last_name',
                    'builder_contact.first_name',
                ),
                'vname' => 'LBL_BUILDER_CONTACT',
                'type' => 'text',
            ),
        ),
);